/**
 * Greek-market insurance product catalog — the seed data for the
 * InsuranceProduct table (recommendation product-matching). Shared by
 * prisma/seed.ts (dev) and scripts/gen-lookup-seed-sql.ts (prod seeding).
 */
export interface CatalogProduct {
    lineOfBusiness: string
    name: { en: string; el: string }
    description: { en: string; el: string }
    category: string
    estimatedAnnualPremium: number
    premiumRangeLow: number | null
    premiumRangeHigh: number | null
    keyBenefits: Array<{ en: string; el: string }>
    idealProfileTags: string[]
    urgencyForProfiles: string
    greekMarketPopularity: number
    sortOrder: number
}

export const PRODUCT_CATALOG: CatalogProduct[] = [
        {
            lineOfBusiness: 'motor',
            name: { en: 'Motor Insurance', el: 'Ασφάλεια Αυτοκινήτου' },
            description: { en: 'Comprehensive or third-party motor coverage for cars, motorcycles, and commercial vehicles.', el: 'Ολική ή ασφάλεια αστικής ευθύνης για αυτοκίνητα, μοτοσικλέτες και επαγγελματικά οχήματα.' },
            category: 'individual',
            estimatedAnnualPremium: 400,
            premiumRangeLow: 180,
            premiumRangeHigh: 1200,
            keyBenefits: [
                { en: 'Third-party liability (mandatory)', el: 'Αστική ευθύνη (υποχρεωτική)' },
                { en: 'Own damage / collision', el: 'Ίδιες ζημιές / σύγκρουση' },
                { en: 'Roadside assistance', el: 'Οδική βοήθεια' },
                { en: 'Legal protection', el: 'Νομική προστασία' },
            ],
            idealProfileTags: ['has_vehicles'],
            urgencyForProfiles: 'critical',
            greekMarketPopularity: 95,
            sortOrder: 1,
        },
        {
            lineOfBusiness: 'home',
            name: { en: 'Home Insurance', el: 'Ασφάλεια Κατοικίας' },
            description: { en: 'Coverage for fire, earthquake, flood, theft, and liability for homeowners and tenants.', el: 'Κάλυψη πυρκαγιάς, σεισμού, πλημμύρας, κλοπής και αστικής ευθύνης για ιδιοκτήτες και ενοικιαστές.' },
            category: 'individual',
            estimatedAnnualPremium: 250,
            premiumRangeLow: 100,
            premiumRangeHigh: 800,
            keyBenefits: [
                { en: 'Fire & natural disasters', el: 'Πυρκαγιά & φυσικές καταστροφές' },
                { en: 'Earthquake (ENFIA compliance)', el: 'Σεισμός (συμβατό με ΕΝΦΙΑ)' },
                { en: 'Theft & vandalism', el: 'Κλοπή & βανδαλισμοί' },
                { en: 'Tenant liability', el: 'Ευθύνη ενοικιαστή' },
            ],
            idealProfileTags: ['homeowner'],
            urgencyForProfiles: 'high',
            greekMarketPopularity: 60,
            sortOrder: 2,
        },
        {
            lineOfBusiness: 'health',
            name: { en: 'Private Health Insurance', el: 'Ιδιωτική Ασφάλεια Υγείας' },
            description: { en: 'Hospitalization, outpatient, and preventive care coverage supplementing ESY (Greek NHS).', el: 'Κάλυψη νοσηλείας, εξωτερικών ιατρείων και προληπτικών εξετάσεων ως συμπλήρωμα του ΕΣΥ.' },
            category: 'individual',
            estimatedAnnualPremium: 800,
            premiumRangeLow: 300,
            premiumRangeHigh: 3000,
            keyBenefits: [
                { en: 'Hospitalization (private rooms)', el: 'Νοσηλεία (ιδιωτικά δωμάτια)' },
                { en: 'Outpatient & diagnostics', el: 'Εξωτερικά ιατρεία & διαγνωστικά' },
                { en: 'Direct billing network', el: 'Δίκτυο απευθείας πληρωμών' },
                { en: 'Annual check-up', el: 'Ετήσιο check-up' },
            ],
            idealProfileTags: [],
            urgencyForProfiles: 'high',
            greekMarketPopularity: 75,
            sortOrder: 3,
        },
        {
            lineOfBusiness: 'life',
            name: { en: 'Life Insurance', el: 'Ασφάλεια Ζωής' },
            description: { en: 'Financial protection for dependents in case of death, disability, or critical illness.', el: 'Οικονομική προστασία εξαρτωμένων μελών σε περίπτωση θανάτου, αναπηρίας ή σοβαρής ασθένειας.' },
            category: 'individual',
            estimatedAnnualPremium: 600,
            premiumRangeLow: 200,
            premiumRangeHigh: 2500,
            keyBenefits: [
                { en: 'Death benefit', el: 'Παροχή θανάτου' },
                { en: 'Permanent disability', el: 'Μόνιμη αναπηρία' },
                { en: 'Critical illness cover', el: 'Κάλυψη σοβαρών ασθενειών' },
                { en: 'Mortgage protection', el: 'Προστασία στεγαστικού δανείου' },
            ],
            idealProfileTags: ['has_dependents', 'has_mortgage', 'has_loans'],
            urgencyForProfiles: 'critical',
            greekMarketPopularity: 50,
            sortOrder: 4,
        },
        {
            lineOfBusiness: 'travel',
            name: { en: 'Travel Insurance', el: 'Ταξιδιωτική Ασφάλεια' },
            description: { en: 'Coverage for medical emergencies, trip cancellation, and luggage loss while traveling.', el: 'Κάλυψη ιατρικών εκτάκτων, ακύρωσης ταξιδιού και απώλειας αποσκευών κατά τη διάρκεια ταξιδιού.' },
            category: 'individual',
            estimatedAnnualPremium: 80,
            premiumRangeLow: 30,
            premiumRangeHigh: 300,
            keyBenefits: [
                { en: 'Emergency medical abroad', el: 'Ιατρικά έκτακτα στο εξωτερικό' },
                { en: 'Trip cancellation', el: 'Ακύρωση ταξιδιού' },
                { en: 'Luggage protection', el: 'Προστασία αποσκευών' },
                { en: 'Repatriation', el: 'Επαναπατρισμός' },
            ],
            idealProfileTags: ['travels_frequently'],
            urgencyForProfiles: 'medium',
            greekMarketPopularity: 40,
            sortOrder: 5,
        },
        {
            lineOfBusiness: 'pet',
            name: { en: 'Pet Insurance', el: 'Ασφάλεια Κατοικίδιου' },
            description: { en: 'Veterinary costs, liability, and theft coverage for dogs and cats.', el: 'Κτηνιατρικά έξοδα, αστική ευθύνη και κάλυψη κλοπής για σκύλους και γάτες.' },
            category: 'individual',
            estimatedAnnualPremium: 150,
            premiumRangeLow: 80,
            premiumRangeHigh: 400,
            keyBenefits: [
                { en: 'Veterinary treatment', el: 'Κτηνιατρική περίθαλψη' },
                { en: 'Leishmaniasis coverage', el: 'Κάλυψη λεϊσμανίασης' },
                { en: 'Third-party liability', el: 'Αστική ευθύνη τρίτων' },
                { en: 'Theft / loss', el: 'Κλοπή / απώλεια' },
            ],
            idealProfileTags: ['has_pets'],
            urgencyForProfiles: 'low',
            greekMarketPopularity: 25,
            sortOrder: 6,
        },
        {
            lineOfBusiness: 'liability',
            name: { en: 'Professional Liability', el: 'Επαγγελματική Ευθύνη' },
            description: { en: 'Errors & omissions coverage for professionals and self-employed individuals.', el: 'Κάλυψη σφαλμάτων και παραλείψεων για επαγγελματίες και ελεύθερους επαγγελματίες.' },
            category: 'individual',
            estimatedAnnualPremium: 200,
            premiumRangeLow: 100,
            premiumRangeHigh: 1000,
            keyBenefits: [
                { en: 'Professional negligence defense', el: 'Υπεράσπιση επαγγελματικής αμέλειας' },
                { en: 'Client claims coverage', el: 'Κάλυψη αξιώσεων πελατών' },
                { en: 'Legal costs', el: 'Νομικά έξοδα' },
            ],
            idealProfileTags: ['self_employed'],
            urgencyForProfiles: 'medium',
            greekMarketPopularity: 30,
            sortOrder: 7,
        },
        {
            lineOfBusiness: 'legal_expenses',
            name: { en: 'Legal Expenses Insurance', el: 'Ασφάλεια Νομικής Προστασίας' },
            description: { en: 'Coverage for legal fees, court costs, and dispute resolution.', el: 'Κάλυψη δικηγορικών αμοιβών, δικαστικών εξόδων και επίλυσης διαφορών.' },
            category: 'individual',
            estimatedAnnualPremium: 120,
            premiumRangeLow: 60,
            premiumRangeHigh: 350,
            keyBenefits: [
                { en: 'Legal consultation', el: 'Νομική συμβουλή' },
                { en: 'Court representation', el: 'Δικαστική εκπροσώπηση' },
                { en: 'Dispute mediation', el: 'Διαμεσολάβηση διαφορών' },
            ],
            idealProfileTags: [],
            urgencyForProfiles: 'low',
            greekMarketPopularity: 20,
            sortOrder: 8,
        },
        {
            lineOfBusiness: 'income_protection',
            name: { en: 'Income Protection', el: 'Προστασία Εισοδήματος' },
            description: { en: 'Replaces income if you are unable to work due to illness or injury.', el: 'Αντικατάσταση εισοδήματος σε περίπτωση αδυναμίας εργασίας λόγω ασθένειας ή τραυματισμού.' },
            category: 'individual',
            estimatedAnnualPremium: 500,
            premiumRangeLow: 200,
            premiumRangeHigh: 1500,
            keyBenefits: [
                { en: 'Monthly income replacement', el: 'Μηνιαία αντικατάσταση εισοδήματος' },
                { en: 'Covers illness & accidents', el: 'Καλύπτει ασθένεια & ατυχήματα' },
                { en: 'Return-to-work support', el: 'Υποστήριξη επιστροφής στην εργασία' },
            ],
            idealProfileTags: ['has_dependents', 'self_employed'],
            urgencyForProfiles: 'high',
            greekMarketPopularity: 20,
            sortOrder: 9,
        },
        {
            lineOfBusiness: 'cyber',
            name: { en: 'Cyber Protection', el: 'Cyber Προστασία' },
            description: { en: 'Cover for online fraud, identity theft and unauthorised card transactions, with legal and technical support.', el: 'Κάλυψη για online απάτη, κλοπή ταυτότητας και μη εξουσιοδοτημένες συναλλαγές, με νομική και τεχνική υποστήριξη.' },
            category: 'individual',
            estimatedAnnualPremium: 90,
            premiumRangeLow: 40,
            premiumRangeHigh: 250,
            keyBenefits: [
                { en: 'Online fraud reimbursement', el: 'Αποζημίωση online απάτης' },
                { en: 'Identity theft support', el: 'Υποστήριξη σε κλοπή ταυτότητας' },
                { en: 'Legal & technical assistance', el: 'Νομική & τεχνική βοήθεια' },
            ],
            idealProfileTags: [],
            urgencyForProfiles: 'low',
            greekMarketPopularity: 15,
            sortOrder: 10,
        },
        {
            lineOfBusiness: 'pension',
            name: { en: 'Pension & Savings Plan', el: 'Συνταξιοδοτικό & Αποταμιευτικό Πρόγραμμα' },
            description: { en: 'Long-term savings or pension programme with defined contributions, maturity options and surrender terms.', el: 'Μακροπρόθεσμο αποταμιευτικό ή συνταξιοδοτικό πρόγραμμα με καθορισμένες εισφορές, επιλογές ωρίμανσης και όρους εξαγοράς.' },
            category: 'individual',
            estimatedAnnualPremium: 1200,
            premiumRangeLow: 400,
            premiumRangeHigh: 6000,
            keyBenefits: [
                { en: 'Defined contribution savings', el: 'Αποταμίευση με καθορισμένες εισφορές' },
                { en: 'Maturity options (lump sum / annuity)', el: 'Επιλογές ωρίμανσης (εφάπαξ / σύνταξη)' },
                { en: 'Optional guaranteed component', el: 'Προαιρετικό εγγυημένο σκέλος' },
            ],
            idealProfileTags: ['employed', 'self_employed'],
            urgencyForProfiles: 'medium',
            greekMarketPopularity: 35,
            sortOrder: 11,
        },
        {
            lineOfBusiness: 'personal_accident',
            name: { en: 'Personal Accident', el: 'Προσωπικό Ατύχημα' },
            description: { en: 'Fixed benefits for accidental injury, disability or death, complementing health and life cover.', el: 'Σταθερές παροχές για τραυματισμό, ανικανότητα ή απώλεια ζωής από ατύχημα, συμπληρωματικά στην υγεία και τη ζωή.' },
            category: 'individual',
            estimatedAnnualPremium: 120,
            premiumRangeLow: 50,
            premiumRangeHigh: 400,
            keyBenefits: [
                { en: 'Accidental disability benefit', el: 'Παροχή ανικανότητας από ατύχημα' },
                { en: 'Hospital cash allowance', el: 'Νοσοκομειακό επίδομα' },
                { en: 'Family payout on accidental death', el: 'Παροχή στην οικογένεια σε απώλεια ζωής από ατύχημα' },
            ],
            idealProfileTags: ['self_employed'],
            urgencyForProfiles: 'low',
            greekMarketPopularity: 25,
            sortOrder: 12,
        },
        {
            lineOfBusiness: 'boat',
            name: { en: 'Boat Insurance', el: 'Ασφάλεια Σκάφους' },
            description: { en: 'Liability and hull cover for leisure boats — mandatory liability applies to Greek waters.', el: 'Αστική ευθύνη και κάλυψη σκάφους αναψυχής — η αστική ευθύνη είναι υποχρεωτική στα ελληνικά ύδατα.' },
            category: 'individual',
            estimatedAnnualPremium: 350,
            premiumRangeLow: 150,
            premiumRangeHigh: 2000,
            keyBenefits: [
                { en: 'Mandatory third-party liability', el: 'Υποχρεωτική αστική ευθύνη' },
                { en: 'Hull & machinery damage', el: 'Ζημιές σκάφους & μηχανής' },
                { en: 'Salvage & wreck removal', el: 'Επιθαλάσσια αρωγή & ανέλκυση' },
            ],
            idealProfileTags: [],
            urgencyForProfiles: 'low',
            greekMarketPopularity: 10,
            sortOrder: 13,
        },
        {
            lineOfBusiness: 'roadside',
            name: { en: 'Roadside Assistance', el: 'Οδική Βοήθεια' },
            description: { en: 'Standalone breakdown assistance: on-the-spot repair, towing and onward travel.', el: 'Αυτόνομη οδική βοήθεια: επιτόπου επισκευή, μεταφορά οχήματος και συνέχιση ταξιδιού.' },
            category: 'individual',
            estimatedAnnualPremium: 60,
            premiumRangeLow: 30,
            premiumRangeHigh: 150,
            keyBenefits: [
                { en: '24/7 breakdown response', el: '24/7 ανταπόκριση σε βλάβη' },
                { en: 'Towing to a garage', el: 'Μεταφορά σε συνεργείο' },
                { en: 'Onward travel / replacement', el: 'Συνέχιση ταξιδιού / αντικατάσταση' },
            ],
            idealProfileTags: ['has_vehicles'],
            urgencyForProfiles: 'low',
            greekMarketPopularity: 55,
            sortOrder: 14,
        },
        {
            lineOfBusiness: 'business',
            name: { en: 'Business Insurance', el: 'Ασφάλεια Επιχείρησης' },
            description: { en: 'Premises, equipment, stock, business interruption and liability cover for small businesses.', el: 'Κάλυψη στέγης, εξοπλισμού, εμπορευμάτων, διακοπής εργασιών και αστικής ευθύνης για μικρές επιχειρήσεις.' },
            category: 'business',
            estimatedAnnualPremium: 800,
            premiumRangeLow: 300,
            premiumRangeHigh: 5000,
            keyBenefits: [
                { en: 'Premises & equipment cover', el: 'Κάλυψη στέγης & εξοπλισμού' },
                { en: 'Business interruption', el: 'Διακοπή εργασιών' },
                { en: 'General & employer liability', el: 'Γενική & εργοδοτική ευθύνη' },
            ],
            idealProfileTags: ['self_employed'],
            urgencyForProfiles: 'medium',
            greekMarketPopularity: 40,
            sortOrder: 15,
        },
        {
            lineOfBusiness: 'group_health',
            name: { en: 'Group Health', el: 'Ομαδική Υγεία' },
            description: { en: 'Employee health cover for businesses: hospital care, outpatient benefits and check-ups.', el: 'Κάλυψη υγείας προσωπικού για επιχειρήσεις: νοσοκομειακή περίθαλψη, εξωνοσοκομειακές παροχές και check-up.' },
            category: 'business',
            estimatedAnnualPremium: 350,
            premiumRangeLow: 150,
            premiumRangeHigh: 1200,
            keyBenefits: [
                { en: 'Hospital cover per employee', el: 'Νοσοκομειακή κάλυψη ανά εργαζόμενο' },
                { en: 'Outpatient & diagnostics', el: 'Εξωνοσοκομειακά & διαγνωστικές' },
                { en: 'Annual check-up', el: 'Ετήσιο check-up' },
            ],
            idealProfileTags: [],
            urgencyForProfiles: 'low',
            greekMarketPopularity: 30,
            sortOrder: 16,
        },
        {
            lineOfBusiness: 'group_pension',
            name: { en: 'Group Pension', el: 'Ομαδική Σύνταξη' },
            description: { en: 'Employer-sponsored pension savings for staff, with defined contributions per employee.', el: 'Συνταξιοδοτική αποταμίευση προσωπικού με εισφορές εργοδότη ανά εργαζόμενο.' },
            category: 'business',
            estimatedAnnualPremium: 600,
            premiumRangeLow: 200,
            premiumRangeHigh: 3000,
            keyBenefits: [
                { en: 'Employer contributions', el: 'Εισφορές εργοδότη' },
                { en: 'Per-employee accounts', el: 'Ατομικοί λογαριασμοί εργαζομένων' },
                { en: 'Vesting & maturity options', el: 'Όροι ωρίμανσης & κατοχύρωσης' },
            ],
            idealProfileTags: [],
            urgencyForProfiles: 'low',
            greekMarketPopularity: 20,
            sortOrder: 17,
        },
        {
            lineOfBusiness: 'group_life',
            name: { en: 'Group Life', el: 'Ομαδική Ζωή' },
            description: { en: 'Employer-paid life cover for staff: a lump-sum benefit for each employee in case of death or permanent disability.', el: 'Ομαδική ασφάλιση ζωής προσωπικού με έξοδα εργοδότη: εφάπαξ κεφάλαιο ανά εργαζόμενο σε περίπτωση θανάτου ή μόνιμης ανικανότητας.' },
            category: 'business',
            estimatedAnnualPremium: 150,
            premiumRangeLow: 50,
            premiumRangeHigh: 600,
            keyBenefits: [
                { en: 'Death benefit per employee', el: 'Κεφάλαιο ζωής ανά εργαζόμενο' },
                { en: 'Permanent disability benefit', el: 'Παροχή μόνιμης ανικανότητας' },
                { en: 'Optional accident riders', el: 'Προαιρετικές καλύψεις ατυχήματος' },
            ],
            idealProfileTags: [],
            urgencyForProfiles: 'low',
            greekMarketPopularity: 25,
            sortOrder: 18,
        },
]
