import { branchLabel } from "@/lib/insurance/taxonomy"
import { isPlaceholderPolicyNumber } from "@/lib/wallet/policy-identity"

/**
 * A document's NAME is generated by us. The user's own file name is never
 * stored, rendered, logged, or sent anywhere.
 *
 * A file name is user-authored metadata and it leaks: `LIFE_POLICY.pdf` shown
 * on a health policy page discloses a life component by name alone, before
 * anyone opens anything. `NIKOS_ETHNIKI_2026.pdf` names a person and an
 * insurer. There is no safe subset — a hash still correlates two uploads of
 * the same file across accounts — so the owner's decision is to keep none of
 * it, in any form.
 *
 * The storage key was already anonymous (`crypto.randomUUID()` + extension);
 * this closes the other half, the one a person actually reads.
 *
 * ONE function serves both writer and reader. Writers call it with whatever is
 * known at creation (usually nothing but the kind, because extraction has not
 * run); readers call it with the extracted policy and get the full label. That
 * is why the stored value can be superseded by the rendered one without either
 * ever containing the original.
 */

export type DocumentLabelInput = {
    documentKind?: string | null
    lineOfBusiness?: string | null
    policyNumber?: string | null
    effectiveFrom?: Date | string | null
    effectiveTo?: Date | string | null
}

function year(value: Date | string | null | undefined): string | null {
    if (!value) return null
    const d = value instanceof Date ? value : new Date(value)
    return Number.isNaN(d.getTime()) ? null : String(d.getUTCFullYear())
}

/** «2025–2026», «2026», or null when the document states no period. */
function periodLabel(input: DocumentLabelInput): string | null {
    const from = year(input.effectiveFrom)
    const to = year(input.effectiveTo)
    if (from && to && from !== to) return `${from}–${to}`
    return from ?? to ?? null
}

function usablePolicyNumber(value: string | null | undefined): string | null {
    if (!value) return null
    // A sentinel is not an identity — see lib/wallet/policy-identity.ts.
    if (isPlaceholderPolicyNumber(value)) return null
    return value
}

export function documentDisplayLabel(
    input: DocumentLabelInput,
    language: "el" | "en" = "el"
): string {
    if (input.documentKind === "renewal_notice") {
        const period = periodLabel(input)
        const base = language === "el" ? "Ανανεωτήριο" : "Renewal"
        return period ? `${base} ${period}` : base
    }

    const number = usablePolicyNumber(input.policyNumber)
    const lob = input.lineOfBusiness

    // Before extraction there is no branch and no number, and inventing one
    // would be worse than saying so.
    if (!lob || lob === "other" || !number) {
        return language === "el" ? "Έγγραφο σε επεξεργασία" : "Document being processed"
    }

    const branch = branchLabel(lob, language)
    const base = language === "el" ? "Ασφαλιστήριο" : "Policy"
    return `${base} ${branch} · ${number}`
}

/**
 * The name the BROWSER saves as, served via Content-Disposition.
 *
 * Not the storage UUID (meaningless in a downloads folder) and not the
 * original. ASCII-only and slugged, because Content-Disposition with raw
 * Greek needs RFC 5987 encoding that not every client handles the same way —
 * and a download that saves as mojibake is worse than a plain one.
 */
export function downloadFileName(input: {
    lineOfBusiness?: string | null
    policyNumber?: string | null
    mimeType?: string | null
}): string {
    const slug = (value: string) =>
        value
            .normalize("NFD")
            .replace(/[̀-ͯ]/g, "")
            .replace(/[^A-Za-z0-9]+/g, "-")
            .replace(/^-+|-+$/g, "")
            .toLowerCase()

    const parts = ["policywallet"]
    if (input.lineOfBusiness && input.lineOfBusiness !== "other") parts.push(slug(input.lineOfBusiness))
    const number = usablePolicyNumber(input.policyNumber)
    if (number) parts.push(slug(number))

    const ext =
        input.mimeType === "application/pdf" ? "pdf"
        : input.mimeType === "image/jpeg" ? "jpg"
        : input.mimeType === "image/png" ? "png"
        : input.mimeType === "image/webp" ? "webp"
        : input.mimeType === "image/heic" ? "heic"
        : "pdf"

    return `${parts.filter(Boolean).join("-") || "policywallet-document"}.${ext}`
}

/**
 * What a writer stores at creation time. Deliberately identical to the
 * rendered label for the same input — there is no second vocabulary.
 */
export function storedDocumentLabel(input: DocumentLabelInput): string {
    return documentDisplayLabel(input, "el")
}

/**
 * The file name sent to a MODEL PROVIDER in the document part of a request.
 *
 * Providers log request metadata, so a filename in the payload leaves our
 * boundary and lands in someone else's telemetry. Every provider needs *a*
 * name for the part; none of them needs a true one, and the extraction has
 * never read it — the prompt does not contain it.
 *
 * Deliberately a CONSTANT per media type, carrying no policy, person, insurer
 * or branch. Not the generated label either: that contains a policy number.
 */
export function providerDocumentFileName(mimeType: string | null | undefined): string {
    switch (mimeType) {
        case "image/jpeg":
            return "document.jpg"
        case "image/png":
            return "document.png"
        case "image/webp":
            return "document.webp"
        case "image/heic":
            return "document.heic"
        default:
            return "document.pdf"
    }
}
