#!/usr/bin/env node
/**
 * Grafí token build: tokens/*.json → app/grafi.css + docs/contrast-matrix.md
 *
 * The JSON is the source of truth. app/grafi.css is GENERATED — never edited by
 * hand; tests/unit/grafi-tokens.test.ts regenerates in-memory and fails on any
 * drift, which is what makes "generated" a fact rather than a comment.
 *
 * WHY THIS EMITS INTO THE EXISTING ARCHITECTURE INSTEAD OF REPLACING IT.
 * app/globals.css is load-bearing: two guards (design-token-debt,
 * token-contrast-contract) read it, and its --radius-* / --color-* names
 * already generate live utilities. Grafí therefore uses NON-COLLIDING names
 * (surface-*, fg-*, state-*, action-*, g-* for space/radius/duration) and is
 * imported after it. Migration of legacy tokens onto Grafí is a later, ratcheted
 * move — the debt guard already counts the stragglers.
 *
 * CONTRAST IS A BUILD GATE, NOT A DOCUMENT. semantic.json declares the pairs
 * and floors; this script measures every one, writes docs/contrast-matrix.md,
 * and EXITS NON-ZERO on a miss — the same discipline as the @on/@min contract
 * in globals.css, applied at generation time.
 *
 * APPLICATION TIER (2026-08-30). The app adds an `alpha` tier (hairlines,
 * scrims, the translucent chrome) referenced as `alpha:<name>` — composited
 * colours are never measured and never used for text, so a contrast check on
 * one is a build error; a `shadow` tier (flat is the default: only `raised`
 * and `overlay` exist); a spring ease; purpose-named radii; type steps that
 * carry their weight and tracking; and the app rhythm (17px/16px base,
 * 26px/32px section gap) emitted as a `:root` media switch.
 */
import { readFileSync, writeFileSync } from 'node:fs'

const prim = JSON.parse(readFileSync('tokens/primitives.json', 'utf8'))
const sem = JSON.parse(readFileSync('tokens/semantic.json', 'utf8'))

const isAlphaRef = (v) => typeof v === 'string' && v.startsWith('alpha:')
const alphaOf = (ref) => {
  const name = ref.slice('alpha:'.length)
  const v = prim.alpha?.[name]
  if (!v) throw new Error(`semantic token references unknown alpha primitive "${name}"`)
  if (!/^rgba?\(/.test(v)) throw new Error(`alpha primitive "${name}" must be rgb()/rgba(): ${v}`)
  return v
}
const hexOf = (name) => {
  const v = prim.color[name]
  if (!v) throw new Error(`semantic token references unknown primitive "${name}"`)
  if (!/^#[0-9A-Fa-f]{6}$/.test(v)) throw new Error(`primitive "${name}" is not 6-digit hex: ${v}`)
  return v
}
const resolve = (ref) => (isAlphaRef(ref) ? alphaOf(ref) : hexOf(ref))

// Reject raw hex in the semantic tier — roles reference names, never values.
for (const theme of ['light', 'dark']) {
  for (const [role, val] of Object.entries(sem[theme])) {
    if (/^#/.test(val)) throw new Error(`semantic.${theme}.${role} is raw hex ("${val}") — reference a primitive name`)
  }
}
// Every role exists in both themes — dark is a real second theme, not a fallback.
for (const role of Object.keys(sem.light)) if (!(role in sem.dark)) throw new Error(`semantic.dark is missing role "${role}"`)
for (const role of Object.keys(sem.dark)) if (!(role in sem.light)) throw new Error(`semantic.light is missing role "${role}"`)

const lum = (hex) => {
  const c = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255)
    .map((v) => (v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4))
  return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]
}
const ratio = (a, b) => { const [x, y] = [lum(a), lum(b)]; return (Math.max(x, y) + 0.05) / (Math.min(x, y) + 0.05) }

// ── contrast gate ──
const rows = []
let failed = 0
for (const theme of ['light', 'dark']) {
  for (const chk of sem.contrastChecks) {
    const fgRef = sem[theme][chk.fg]; const bgRef = sem[theme][chk.bg]
    if (fgRef === undefined || bgRef === undefined) throw new Error(`contrastChecks names an unknown role: ${chk.fg} / ${chk.bg}`)
    if (isAlphaRef(fgRef) || isAlphaRef(bgRef)) throw new Error(`contrastChecks ${chk.fg}/${chk.bg}: alpha roles are composited and cannot be measured — never use one for text`)
    const fgHex = hexOf(fgRef); const bgHex = hexOf(bgRef)
    const r = ratio(fgHex, bgHex)
    const ok = r >= chk.min
    if (!ok) failed++
    rows.push({ theme, fgRole: chk.fg, bgRole: chk.bg, fgHex, bgHex, min: chk.min, nonText: chk.nonText, note: chk.note, r: r.toFixed(2), ok })
  }
}
// Every text-bearing role is measured somewhere: a role with no check is a hole, not a pass.
const measured = new Set(sem.contrastChecks.map((c) => c.fg))
for (const role of Object.keys(sem.light)) {
  const textLike = /^(fg-|state-(covered|gap|review)$)/.test(role)
  if (textLike && !measured.has(role)) throw new Error(`role "${role}" is a text colour with no contrastChecks entry`)
}
const alphaRoles = Object.entries(sem.light).filter(([, v]) => isAlphaRef(v)).map(([k]) => k)
const matrix2 = `# Contrast matrix — generated by \`npm run tokens\` — do not edit

Every declared pair, both themes, measured at generation time. **A miss fails the token build**,
so a value change that breaks a floor cannot produce a stylesheet. Floors: 4.5 text (1.4.3 AA) ·
3 non-text (1.4.11). Rows marked *decorative* carry no identification claim.

| theme | fg | bg | measured | floor | verdict |
|---|---|---|---|---|---|
${rows.map((r) => `| ${r.theme} | ${r.fgRole} \`${r.fgHex}\` | ${r.bgRole} \`${r.bgHex}\` | **${r.r}:1** | ${r.min}${r.nonText ? ' (non-text)' : ''}${r.note ? ' *decorative*' : ''} | ${r.ok ? 'PASS' : '**FAIL**'} |`).join('\n')}

## Composited roles — not measured, never text

${alphaRoles.map((k) => `- \`${k}\`: light \`${resolve(sem.light[k])}\`, dark \`${resolve(sem.dark[k])}\``).join('\n')}

A translucent chrome or scrim takes its contrast from whatever it composites over; the build
refuses a contrast check on one, and every component that uses one carries a solid fallback
(\`@supports not (backdrop-filter: blur(1px))\`) and honours \`prefers-reduced-transparency\`.
`
writeFileSync('docs/contrast-matrix.md', matrix2)
if (failed) { console.error(`✗ ${failed} contrast pair(s) below floor — see docs/contrast-matrix.md`); process.exit(1) }

// ── emit CSS ──
const cssVars = (theme, indent = '  ') =>
  Object.entries(sem[theme]).map(([k, v]) => `${indent}--${k}: ${resolve(v)};`).join('\n')
const primVars = Object.entries(prim.color).map(([k, v]) => `  --g-${k}: ${v};`).join('\n')
const alphaVars = Object.entries(prim.alpha ?? {}).map(([k, v]) => `  --g-alpha-${k}: ${v};`).join('\n')
const shadowVars = Object.entries(prim.shadow ?? {}).map(([k, v]) => `  --shadow-g-${k}: ${v};`).join('\n')
const spaceVars = Object.entries(prim.space).map(([k, v]) => `  --spacing-g-${k}: ${v};`).join('\n')
const typeVars = Object.entries(prim.type).map(([k, v]) => {
  const lines = [`  --text-g-${k}: ${v.size};`, `  --text-g-${k}--line-height: ${v.lh};`]
  if (v.weight) lines.push(`  --text-g-${k}--font-weight: ${v.weight};`)
  if (v.tracking) lines.push(`  --text-g-${k}--letter-spacing: ${v.tracking};`)
  return lines.join('\n')
}).join('\n')
const radiusVars = Object.entries(prim.radius).map(([k, v]) => `  --radius-g-${k}: ${v};`).join('\n')
const themeColors = Object.keys(sem.light).map((k) => `  --color-${k}: var(--${k});`).join('\n')
const themeShadows = Object.keys(prim.shadow ?? {}).map((k) => `  --shadow-g-${k}: var(--shadow-g-${k});`).join('\n')
const rhythm = prim.rhythm ?? {}
const breakpointVars = Object.entries(prim.breakpoint ?? {}).map(([k, v]) => `  --breakpoint-${k}: ${v};`).join('\n')

const css = `/* GENERATED by scripts/build-tokens.mjs from tokens/*.json — DO NOT EDIT.
 * Edit the JSON and run \`npm run tokens\`. tests/unit/grafi-tokens.test.ts
 * fails when this file drifts from a fresh generation. */

:root {
  /* Grafí primitives (raw scale — components never reference these) */
${primVars}

  /* Grafí alpha primitives — composited hairlines, scrims, translucent chrome */
${alphaVars}

  /* Grafí elevation — flat is the default; these are the only two shadows */
${shadowVars}

  /* Grafí semantic roles — light */
${cssVars('light')}

  --space-section: clamp(66px, 7vw, 116px);
  /* App rhythm: iOS body 17px on phones, 16px from tablet up; section gap 26/32 */
  --text-g-app-base: ${rhythm['app-base']?.mobile ?? '17px'};
  --space-app-section: ${rhythm['app-section']?.mobile ?? '26px'};
  --dur-fast: ${prim.duration.fast};
  --dur-base: ${prim.duration.base};
  --dur-slow: ${prim.duration.slow};
  --dur-entrance: ${prim.duration.entrance};
  --ease-out-g: ${prim.ease.out};
  --ease-spring-g: ${prim.ease.spring};
}

@media (min-width: 768px) {
  :root {
    --text-g-app-base: ${rhythm['app-base']?.desktop ?? '16px'};
    --space-app-section: ${rhythm['app-section']?.desktop ?? '32px'};
  }
}

.dark {
  /* Grafí semantic roles — dark: a real second theme, not a dimmed light one */
${cssVars('dark')}
}

@theme inline {
  /* Semantic roles as Tailwind utilities: bg-surface-raised, text-fg-brand,
   * border-border-subtle, bg-state-gap-fill … Names chosen NOT to collide with
   * the legacy globals.css namespace. */
${themeColors}

  /* Namespaced scales — rounded-g-lg, rounded-g-card, p-g-6 … legacy --radius-* stays intact. */
${spaceVars}
${radiusVars}

  /* Elevation utilities: shadow-g-raised, shadow-g-overlay */
${themeShadows}

  /* Shell breakpoints: tablet: (768px, the rail) and desk: (1100px, the sidebar) */
${breakpointVars}

  /* Motion: ease-g-out (everything), ease-g-spring (presses) */
  --ease-g-out: var(--ease-out-g);
  --ease-g-spring: var(--ease-spring-g);

  /* Grafi type ladder - text-g-display-xl ... text-g-label, and the app steps
   * text-g-title-lg / title / heading / row / app-body … Line-heights, weights
   * and tracking ride along per Tailwind 4 convention. */
${typeVars}
}
`
writeFileSync('app/grafi.css', css)
console.log(`✓ app/grafi.css (${css.length}B) · docs/contrast-matrix.md (${rows.length} pairs, all ≥ floor; ${alphaRoles.length} composited roles listed)`)
