#!/usr/bin/env node
/**
 * Grafí token build: tokens/*.json → app/grafi.css + docs/contrast-matrix.md
 *
 * The JSON is the source of truth. app/grafi.css is GENERATED — never edited by
 * hand; tests/unit/grafi-tokens.test.ts regenerates in-memory and fails on any
 * drift, which is what makes "generated" a fact rather than a comment.
 *
 * WHY THIS EMITS INTO THE EXISTING ARCHITECTURE INSTEAD OF REPLACING IT.
 * app/globals.css is load-bearing: two guards (design-token-debt,
 * token-contrast-contract) read it, and its --radius-* / --color-* names
 * already generate live utilities. Grafí therefore uses NON-COLLIDING names
 * (surface-*, fg-*, state-*, action-*, g-* for space/radius/duration) and is
 * imported after it. Migration of legacy tokens onto Grafí is a later, ratcheted
 * move — the debt guard already counts the 124 stragglers.
 *
 * CONTRAST IS A BUILD GATE, NOT A DOCUMENT. semantic.json declares the pairs
 * and floors; this script measures every one, writes docs/contrast-matrix.md,
 * and EXITS NON-ZERO on a miss — the same discipline as the @on/@min contract
 * in globals.css, applied at generation time.
 */
import { readFileSync, writeFileSync } from 'node:fs'

const prim = JSON.parse(readFileSync('tokens/primitives.json', 'utf8'))
const sem = JSON.parse(readFileSync('tokens/semantic.json', 'utf8'))

const hexOf = (name) => {
  const v = prim.color[name]
  if (!v) throw new Error(`semantic token references unknown primitive "${name}"`)
  if (!/^#[0-9A-Fa-f]{6}$/.test(v)) throw new Error(`primitive "${name}" is not 6-digit hex: ${v}`)
  return v
}
// Reject raw hex in the semantic tier — roles reference names, never values.
for (const theme of ['light', 'dark']) {
  for (const [role, val] of Object.entries(sem[theme])) {
    if (/^#/.test(val)) throw new Error(`semantic.${theme}.${role} is raw hex ("${val}") — reference a primitive name`)
  }
}

const lum = (hex) => {
  const c = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255)
    .map((v) => (v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4))
  return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]
}
const ratio = (a, b) => { const [x, y] = [lum(a), lum(b)]; return (Math.max(x, y) + 0.05) / (Math.min(x, y) + 0.05) }

// ── contrast gate ──
const rows = []
let failed = 0
for (const theme of ['light', 'dark']) {
  for (const chk of sem.contrastChecks) {
    const fgHex = hexOf(sem[theme][chk.fg]); const bgHex = hexOf(sem[theme][chk.bg])
    const r = ratio(fgHex, bgHex)
    const ok = r >= chk.min
    if (!ok) failed++
    rows.push({ theme, fgRole: chk.fg, bgRole: chk.bg, fgHex, bgHex, min: chk.min, nonText: chk.nonText, note: chk.note, r: r.toFixed(2), ok })
  }
}
const matrix2 = `# Contrast matrix — generated by \`npm run tokens\` — do not edit

Every declared pair, both themes, measured at generation time. **A miss fails the token build**,
so a value change that breaks a floor cannot produce a stylesheet. Floors: 4.5 text (1.4.3 AA) ·
3 non-text (1.4.11). Rows marked *decorative* carry no identification claim.

| theme | fg | bg | measured | floor | verdict |
|---|---|---|---|---|---|
${rows.map((r) => `| ${r.theme} | ${r.fgRole} \`${r.fgHex}\` | ${r.bgRole} \`${r.bgHex}\` | **${r.r}:1** | ${r.min}${r.nonText ? ' (non-text)' : ''}${r.note ? ' *decorative*' : ''} | ${r.ok ? 'PASS' : '**FAIL**'} |`).join('\n')}
`
writeFileSync('docs/contrast-matrix.md', matrix2)
if (failed) { console.error(`✗ ${failed} contrast pair(s) below floor — see docs/contrast-matrix.md`); process.exit(1) }

// ── emit CSS ──
const cssVars = (theme, indent = '  ') =>
  Object.entries(sem[theme]).map(([k, v]) => `${indent}--${k}: ${hexOf(v)};`).join('\n')
const primVars = Object.entries(prim.color).map(([k, v]) => `  --g-${k}: ${v};`).join('\n')
const spaceVars = Object.entries(prim.space).map(([k, v]) => `  --spacing-g-${k}: ${v};`).join('\n')
const typeVars = Object.entries(prim.type).map(([k, v]) => `  --text-g-${k}: ${v.size};\n  --text-g-${k}--line-height: ${v.lh};`).join('\n')
const radiusVars = Object.entries(prim.radius).map(([k, v]) => `  --radius-g-${k}: ${v};`).join('\n')
const themeColors = Object.keys(sem.light).map((k) => `  --color-${k}: var(--${k});`).join('\n')

const css = `/* GENERATED by scripts/build-tokens.mjs from tokens/*.json — DO NOT EDIT.
 * Edit the JSON and run \`npm run tokens\`. tests/unit/grafi-tokens.test.ts
 * fails when this file drifts from a fresh generation. */

:root {
  /* Grafí primitives (raw scale — components never reference these) */
${primVars}

  /* Grafí semantic roles — light */
${cssVars('light')}

  --space-section: clamp(66px, 7vw, 116px);
  --dur-fast: ${prim.duration.fast};
  --dur-base: ${prim.duration.base};
  --dur-slow: ${prim.duration.slow};
  --dur-entrance: ${prim.duration.entrance};
  --ease-out-g: ${prim.ease.out};
}

.dark {
  /* Grafí semantic roles — dark: a real second theme, not a dimmed light one */
${cssVars('dark')}
}

@theme inline {
  /* Semantic roles as Tailwind utilities: bg-surface-raised, text-fg-brand,
   * border-border-subtle, bg-state-gap-fill … Names chosen NOT to collide with
   * the legacy globals.css namespace. */
${themeColors}

  /* Namespaced scales — rounded-g-lg, p-g-6 … legacy --radius-* stays intact. */
${spaceVars}
${radiusVars}

  /* Grafi type ladder - text-g-display-xl ... text-g-label. Fluid where the
   * brief specifies; line-heights ride along per Tailwind 4 convention. */
${typeVars}
}
`
writeFileSync('app/grafi.css', css)
console.log(`✓ app/grafi.css (${css.length}B) · docs/contrast-matrix.md (${rows.length} pairs, all ≥ floor)`)
