/**
 * Print the catalogue alignment as SQL, for a database this machine cannot
 * connect to.
 *
 * `align:gap-catalogue` is the normal path: it upserts by slug through Prisma
 * and needs a connection string. Production is reached from here through the
 * Supabase MCP instead, so the same write has to travel as SQL text.
 *
 * The statements are the align script's semantics, exactly: UPSERT BY SLUG, so
 * an existing row keeps its id and every `gap_instances` row that references it
 * survives. Nothing is deleted. `created_at` is left to the column default on
 * insert and `updated_at` is stamped on both paths, which is what Prisma's
 * `@updatedAt` does.
 *
 * A row that is active in the database but not authored here is NOT touched by
 * this output — the align script deactivates those, and the caller must check
 * for them separately (production carried none on 2026-09-08).
 *
 * Run: npx tsx scripts/print-gap-catalogue-sql.ts > /tmp/align.sql
 */
import { AUTHORED_GAP_DEFINITIONS } from "../lib/gaps/authored-catalogue"
import { fingerprintGapDefinitions } from "../lib/gaps/catalogue-version"

/** Single-quote a value for Postgres, doubling any quote inside it. */
function lit(value: string): string {
    return `'${value.replace(/'/g, "''")}'`
}

const rows = AUTHORED_GAP_DEFINITIONS
console.log(`-- ${rows.length} authored gap definitions, fingerprint ${fingerprintGapDefinitions(rows as never)}`)
console.log("-- Generated by scripts/print-gap-catalogue-sql.ts — upsert by slug, no deletes.")
console.log("BEGIN;")

for (const d of rows) {
    console.log(
        `INSERT INTO gap_definitions (gap_definition_id, slug, name, title, description, line_of_business, severity, default_severity, rule_id, detection_logic, is_active, updated_at) VALUES (` +
            `gen_random_uuid()::text, ${lit(d.slug)}, ${lit(d.name)}, ${lit(d.title)}, ${lit(d.description)}, ` +
            `${lit(d.lineOfBusiness)}, ${lit(d.severity)}, ${lit(d.defaultSeverity)}, ${lit(d.ruleId)}, ` +
            `${lit(JSON.stringify(d.detectionLogic))}::jsonb, ${d.isActive}, now()) ` +
            `ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, title=EXCLUDED.title, description=EXCLUDED.description, ` +
            `line_of_business=EXCLUDED.line_of_business, severity=EXCLUDED.severity, default_severity=EXCLUDED.default_severity, ` +
            `rule_id=EXCLUDED.rule_id, detection_logic=EXCLUDED.detection_logic, is_active=EXCLUDED.is_active, ` +
            `version=gap_definitions.version + 1, updated_at=now();`
    )
}

console.log("COMMIT;")
