import type { LucideIcon } from "lucide-react"
import {
    Briefcase,
    Car,
    Gavel,
    Gem,
    Heart,
    HeartHandshake,
    Home,
    PawPrint,
    PiggyBank,
    Plane,
    Sailboat,
    Scale,
    ShieldCheck,
    TrendingUp,
    Umbrella,
    Users,
} from "lucide-react"

export interface ProductCategory {
    id: string
    href: string
    icon: LucideIcon
    labelEl: string
    labelEn: string
    tagEl: string
    tagEn: string
    headlineEl: string
    headlineEn: string
    descEl: string
    descEn: string
    surface: string
    border: string
    tagBg: string
}

export const productCategories = [
    {
        id: "motor",
        href: "/product/motor",
        icon: Car,
        labelEl: "Αυτοκίνητο",
        labelEn: "Motor",
        tagEl: "Οχήματα",
        tagEn: "Vehicles",
        // "Market value tracking" would imply an external price feed. The
        // real capability: we surface what the policy would pay; the reader
        // compares it with what the car is worth.
        headlineEl: "Τι θα πλήρωνε το ασφαλιστήριο — και κενά οδικής βοήθειας.",
        headlineEn: "What the policy would pay — and roadside assistance gaps.",
        descEl: "Δείτε την αποζημίωση που προβλέπει το ασφαλιστήριό σας και — με το Family — τι λείπει από την οδική βοήθεια.",
        descEn: "See the payout your policy provides and — with Family — what is missing from your roadside assistance.",
        surface: "bg-[#DCEBDA]",
        border: "border-[#A7F3D0]",
        tagBg: "bg-[#F0FDF4] text-[#166534]",
    },
    {
        id: "property",
        href: "/product/property",
        icon: Home,
        labelEl: "Κατοικία",
        labelEn: "Property",
        tagEl: "Περιουσία",
        tagEn: "Real estate",
        headlineEl: "Κόστος ανακατασκευής και έκπτωση ΕΝΦΙΑ, με μια ματιά.",
        headlineEn: "Rebuild cost and the ENFIA tax discount, at a glance.",
        // Underinsurance detection is a Plus output — the glossary hooks for
        // «υπασφάλιση» and «ασφαλισμένο κεφάλαιο» name the plan, so this does too.
        descEl: "Με το Family, δείτε αν το σπίτι σας είναι ασφαλισμένο για λιγότερα απ' όσο κοστίζει να ξαναχτιστεί.",
        descEn: "With Family, see whether your home is insured for less than it would cost to rebuild.",
        surface: "bg-[#DCEBDA]",
        border: "border-[#A7F3D0]",
        tagBg: "bg-[#F0FDF4] text-[#166534]",
    },
    {
        id: "health",
        href: "/product/health",
        icon: Heart,
        labelEl: "Υγεία",
        labelEn: "Health",
        tagEl: "Ζωή & Υγεία",
        tagEn: "Life & Health",
        headlineEl: "Πόσα πληρώνετε από την τσέπη σας και πού χρεώνεται απευθείας.",
        headlineEn: "What you pay out of pocket and where the hospital bills the insurer directly.",
        descEl: "Ξέρετε πόσο θα πληρώσετε πριν μπείτε σε νοσοκομείο, όχι αφού λάβετε τον λογαριασμό.",
        descEn: "Know how much you will pay before you walk into a hospital, not after the bill arrives.",
        surface: "bg-[#DCEBDA]",
        border: "border-[#A7F3D0]",
        tagBg: "bg-[#F0FDF4] text-[#166534]",
    },
    {
        id: "cyber",
        href: "/product/cyber",
        icon: ShieldCheck,
        labelEl: "Κυβερνοασφάλεια",
        labelEn: "Cyber",
        tagEl: "Ψηφιακή Ασφάλεια",
        tagEn: "Digital security",
        headlineEl: "Κάλυψη για ransomware και για τη διακοπή της δουλειάς σας.",
        headlineEn: "Cover for ransomware and for your work coming to a stop.",
        // The incident response team belongs to the insurer, not to us — the
        // copy says what the policy provides, not what we provide.
        descEl: "Δείτε τι προβλέπει το ασφαλιστήριό σας για την ώρα της επίθεσης — χωρίς ψάξιμο σε παλιά έγγραφα.",
        descEn: "See what your policy provides for the moment of an attack — no digging through old documents.",
        surface: "bg-white",
        border: "border-[#E2E8F0]",
        tagBg: "bg-[#F1F5F9] text-[#475569]",
    },
    {
        id: "liability",
        href: "/product/liability",
        icon: Scale,
        labelEl: "Αστική Ευθύνη",
        labelEn: "Liability",
        tagEl: "Τρίτοι",
        tagEn: "Third parties",
        headlineEl: "Ζημιές σε τρίτους — και έλεγχος για διπλή κάλυψη.",
        headlineEn: "Third-party damage — with a double-coverage check.",
        // The double-coverage check is Plus-only — the teaser names the plan.
        descEl: "Η αστική ευθύνη συχνά υπάρχει ήδη μέσα στο ασφαλιστήριο κατοικίας σας. Με το Family, δείτε αν την πληρώνετε δύο φορές.",
        descEn: "Liability cover often already sits inside your home policy. With Family, see if you are paying for it twice.",
        surface: "bg-[#DCEBDA]",
        border: "border-[#A7F3D0]",
        tagBg: "bg-[#F0FDF4] text-[#166534]",
    },
    {
        id: "legal-expenses",
        href: "/product/legal-expenses",
        icon: Gavel,
        labelEl: "Νομική Προστασία",
        labelEn: "Legal Expenses",
        tagEl: "Νομικά",
        tagEn: "Legal",
        headlineEl: "Δικηγόροι και δικαστήρια: τι πληρώνει το ασφαλιστήριο.",
        headlineEn: "Lawyers and courts: what your policy pays for.",
        descEl: "Τροχαία, εργασιακές και καταναλωτικές διαφορές. Δείτε ποιες υποθέσεις καλύπτονται και ποιες εξαιρούνται.",
        descEn: "Traffic, employment and consumer disputes. See which cases are covered and which are excluded.",
        surface: "bg-[#DCEBDA]",
        border: "border-[#A7F3D0]",
        tagBg: "bg-[#F0FDF4] text-[#166534]",
    },
    {
        id: "group-health",
        href: "/product/group-health",
        icon: Users,
        labelEl: "Ομαδική Υγεία",
        labelEn: "Group Health",
        tagEl: "Εταιρικό",
        tagEn: "Corporate",
        headlineEl: "Συντονισμός εταιρικών παροχών με ατομική κάλυψη.",
        headlineEn: "Coordinate corporate benefits with personal coverage.",
        descEl: "Με το Family, σταματάτε να πληρώνετε δύο φορές για το ίδιο πράγμα. Χαρτογραφήστε τα κενά ανάμεσα σε εταιρικό και ατομικό.",
        descEn: "With Family, you stop double-paying for overlapping benefits. Map the blind spots between your employer plan and personal policy.",
        surface: "bg-white",
        border: "border-[#E2E8F0]",
        tagBg: "bg-[#F1F5F9] text-[#475569]",
    },
    {
        id: "group-life",
        href: "/product/group-life",
        icon: Umbrella,
        labelEl: "Ομαδική Ζωή",
        labelEn: "Group Life",
        tagEl: "Εταιρικό",
        tagEn: "Corporate",
        headlineEl: "Κεφάλαιο ζωής και ανικανότητας για κάθε εργαζόμενο.",
        headlineEn: "Life and disability capital for every employee.",
        descEl: "Η παροχή που ολοκληρώνει το πακέτο δίπλα στην ομαδική υγεία και σύνταξη. Δείτε ποιος καλύπτεται και με πόσα.",
        descEn: "The benefit that completes the package next to group health and pension. See who is covered and for how much.",
        surface: "bg-white",
        border: "border-[#E2E8F0]",
        tagBg: "bg-[#F1F5F9] text-[#475569]",
    },
    {
        id: "group-pension",
        href: "/product/group-pension",
        icon: TrendingUp,
        labelEl: "Ομαδική Σύνταξη",
        labelEn: "Group Pension",
        tagEl: "Συνταξιοδότηση",
        tagEn: "Retirement",
        // "When to retire" would be retirement ADVICE — the regulated line
        // this product does not cross. The card states what the page shows:
        // document facts about leaving, amounts built up, and tax relief.
        headlineEl: "Εισφορές, εργοδοτική συμμετοχή και φορολογικές εκπτώσεις, καθαρά.",
        headlineEn: "Contributions, employer match and tax deductions, made clear.",
        descEl: "Ξέρετε τι ισχύει όταν αποχωρήσετε, πόσα έχετε συγκεντρώσει και τι φορολογικές εκπτώσεις σας ανήκουν.",
        descEn: "Know what happens when you leave, how much you have built up, and what tax deductions you are entitled to.",
        surface: "bg-white",
        border: "border-[#E2E8F0]",
        tagBg: "bg-[#F1F5F9] text-[#475569]",
    },
    {
        id: "life",
        href: "/product/life",
        icon: HeartHandshake,
        labelEl: "Ζωή",
        labelEn: "Life",
        tagEl: "Οικογένεια",
        tagEn: "Family",
        headlineEl: "Κεφάλαιο κάλυψης, σοβαρές ασθένειες και προστασία δανείου.",
        headlineEn: "Cover amount, serious illness and mortgage protection.",
        descEl: "Δείτε αν το κεφάλαιο του ασφαλιστηρίου ζωής σας φτάνει πραγματικά για την οικογένεια και το στεγαστικό σας.",
        descEn: "See whether your life policy's capital actually covers your family and your outstanding mortgage.",
        surface: "bg-[#DCEBDA]",
        border: "border-[#A7F3D0]",
        tagBg: "bg-[#F0FDF4] text-[#166534]",
    },
    {
        id: "travel",
        href: "/product/travel",
        icon: Plane,
        labelEl: "Ταξιδιωτική",
        labelEn: "Travel",
        tagEl: "Ταξίδια",
        tagEn: "Trips",
        headlineEl: "Ιατρικά έκτακτα, ακύρωση ταξιδιού και όρια για Σένγκεν.",
        headlineEn: "Emergency medical abroad, trip cancellation and Schengen limits.",
        descEl: "Μάθετε τι καλύπτει η ταξιδιωτική σας ασφάλεια — και αν τα όρια αρκούν για βίζα — πριν φύγετε, όχι στο ταμείο του νοσοκομείου.",
        descEn: "Know what your travel policy covers — and whether limits meet visa requirements — before you fly, not at a foreign hospital.",
        surface: "bg-[#DCEBDA]",
        border: "border-[#A7F3D0]",
        tagBg: "bg-[#F0FDF4] text-[#166534]",
    },
    {
        id: "pension",
        href: "/product/pension",
        icon: PiggyBank,
        labelEl: "Σύνταξη & Αποταμίευση",
        labelEn: "Pension & Savings",
        tagEl: "Μέλλον",
        tagEn: "Future",
        headlineEl: "Εισφορές, ωρίμανση και όροι εξαγοράς χωρίς ψιλά γράμματα.",
        headlineEn: "Contributions, maturity and surrender terms without fine print.",
        descEl: "Καταλάβετε τι έχετε συμφωνήσει: εφάπαξ ή σύνταξη, εγγυημένο σκέλος και τι χάνετε αν εξαγοράσετε νωρίς.",
        descEn: "Understand what you signed: lump sum or annuity, guaranteed component, and what an early surrender costs you.",
        surface: "bg-[#DCEBDA]",
        border: "border-[#A7F3D0]",
        tagBg: "bg-[#F0FDF4] text-[#166534]",
    },
    {
        id: "boat",
        href: "/product/boat",
        icon: Sailboat,
        labelEl: "Σκάφος",
        labelEn: "Boat",
        tagEl: "Θάλασσα",
        tagEn: "Marine",
        headlineEl: "Υποχρεωτική αστική ευθύνη και κάλυψη σκάφους & μηχανής.",
        headlineEn: "Mandatory liability plus hull & machinery coverage.",
        descEl: "Η αστική ευθύνη είναι υποχρεωτική στα ελληνικά ύδατα. Δείτε τι άλλο καλύπτει το ασφαλιστήριό σας πριν λύσετε κάβους.",
        descEn: "Liability cover is mandatory in Greek waters. See what else your policy includes before you cast off.",
        surface: "bg-[#DCEBDA]",
        border: "border-[#A7F3D0]",
        tagBg: "bg-[#F0FDF4] text-[#166534]",
    },
    {
        // Added with the insurance intelligence expansion: fine art is the one
        // genuinely NEW consumer line it introduced (scheduled items at agreed
        // values). The capability claims below stay inside what shipped — we
        // read the schedule, the values and the security conditions; we do not
        // value anything.
        id: "fine-art",
        href: "/product/fine-art",
        icon: Gem,
        labelEl: "Έργα Τέχνης & Τιμαλφή",
        labelEn: "Fine Art & Valuables",
        tagEl: "Συλλογές",
        tagEn: "Collections",
        headlineEl: "Κάθε έργο με τη δική του αξία — και τους όρους που την κρατούν σε ισχύ.",
        headlineEn: "Each piece at its own value — and the conditions that keep it in force.",
        descEl: "Διαβάζουμε την κατάσταση αντικειμένων, τις συμφωνημένες αξίες και τους όρους ασφαλείας — όπως τον συναγερμό που το ασφαλιστήριο θεωρεί δεδομένο.",
        descEn: "We read the schedule of items, the agreed values and the security conditions — like the alarm your policy takes for granted.",
        surface: "bg-white",
        border: "border-[#E2E8F0]",
        tagBg: "bg-[#F1F5F9] text-[#475569]",
    },
    {
        id: "business",
        href: "/product/business",
        icon: Briefcase,
        labelEl: "Επιχείρηση",
        labelEn: "Business",
        tagEl: "Επαγγελματικό",
        tagEn: "Commercial",
        headlineEl: "Στέγη, εξοπλισμός, διακοπή εργασιών και ευθύνες μαζί.",
        headlineEn: "Premises, equipment, interruption and liabilities in one view.",
        descEl: "Το πολυασφαλιστήριο της επιχείρησής σας έχει πολλά σκέλη. Δείτε ποια έχετε και ποια λείπουν, σε μία εικόνα.",
        descEn: "A business multi-risk policy has many sections. See which ones you hold and which are missing, at a glance.",
        surface: "bg-white",
        border: "border-[#E2E8F0]",
        tagBg: "bg-[#F1F5F9] text-[#475569]",
    },
    {
        id: "pet",
        href: "/product/pet",
        icon: PawPrint,
        labelEl: "Κατοικίδια",
        labelEn: "Pet",
        tagEl: "Ζώα Συντροφιάς",
        tagEn: "Companion animals",
        headlineEl: "Καλύπτεται η λεϊσμανίαση; Και ποιες παθήσεις εξαιρούνται;",
        headlineEn: "Is leishmaniasis covered? And which conditions are excluded?",
        descEl: "Ξέρετε ακριβώς τι καλύπτεται και τι δεν καλύπτεται πριν ο κτηνίατρος σας δώσει τον λογαριασμό.",
        descEn: "Know exactly what's covered and what isn't before the vet hands you the bill.",
        surface: "bg-[#DCEBDA]",
        border: "border-[#A7F3D0]",
        tagBg: "bg-[#F0FDF4] text-[#166534]",
    },
] as const satisfies readonly ProductCategory[]

export type ProductCategoryId = (typeof productCategories)[number]["id"]

export function getProductCategory(id: ProductCategoryId) {
    return productCategories.find((category) => category.id === id)
}
