import type { LucideIcon } from "lucide-react"
import {
    Briefcase,
    Car,
    Gavel,
    Heart,
    HeartHandshake,
    Home,
    PawPrint,
    PiggyBank,
    Plane,
    Sailboat,
    Scale,
    ShieldCheck,
    TrendingUp,
    Umbrella,
    Users,
} from "lucide-react"

export interface ProductCategory {
    id: string
    href: string
    icon: LucideIcon
    labelEl: string
    labelEn: string
    tagEl: string
    tagEn: string
    headlineEl: string
    headlineEn: string
    descEl: string
    descEn: string
    surface: string
    border: string
    tagBg: string
}

export const productCategories = [
    {
        id: "motor",
        href: "/product/motor",
        icon: Car,
        labelEl: "Αυτοκίνητο",
        labelEn: "Motor",
        tagEl: "Οχήματα",
        tagEn: "Vehicles",
        headlineEl: "Έλεγχος αγοραίας αξίας και κενών οδικής βοήθειας.",
        headlineEn: "Real-time market value tracking and roadside gap detection.",
        descEl: "Παρακολουθήστε αν η ασφαλιστική αποζημίωση ακολουθεί την αξία του οχήματός σας και εντοπίστε κενά πριν τα χρειαστείτε.",
        descEn: "Know exactly if your payout keeps pace with your car's real value and catch dangerous roadside gaps before a breakdown.",
        surface: "bg-[#DCEBDA]",
        border: "border-[#A7F3D0]",
        tagBg: "bg-[#F0FDF4] text-[#166534]",
    },
    {
        id: "property",
        href: "/product/property",
        icon: Home,
        labelEl: "Κατοικία",
        labelEn: "Property",
        tagEl: "Περιουσία",
        tagEn: "Real estate",
        headlineEl: "Rebuild Cost Guard και ΕΝΦΙΑ compliance σε δευτερόλεπτα.",
        headlineEn: "Rebuild Cost Guard and ENFIA tax compliance in seconds.",
        descEl: "Εντοπίστε υπο-ασφάλιση ακινήτου πριν καταστροφή σβήσει την αξία που χτίσατε χρόνια.",
        descEn: "Catch under-coverage before a disaster erases the equity you spent years building.",
        surface: "bg-[#DCEBDA]",
        border: "border-[#A7F3D0]",
        tagBg: "bg-[#F0FDF4] text-[#166534]",
    },
    {
        id: "health",
        href: "/product/health",
        icon: Heart,
        labelEl: "Υγεία",
        labelEn: "Health",
        tagEl: "Ζωή & Υγεία",
        tagEn: "Life & Health",
        headlineEl: "Out-of-Pocket αποτύπωση και direct-billing κατευθύνσεις.",
        headlineEn: "Out-of-pocket caps and direct-billing hospital linkups.",
        descEl: "Ξέρετε πόσο θα πληρώσετε πριν μπείτε σε νοσοκομείο, όχι αφού λάβετε τον λογαριασμό.",
        descEn: "Know your maximum exposure before you walk into a hospital, not after the bill arrives.",
        surface: "bg-[#DCEBDA]",
        border: "border-[#A7F3D0]",
        tagBg: "bg-[#F0FDF4] text-[#166534]",
    },
    {
        id: "cyber",
        href: "/product/cyber",
        icon: ShieldCheck,
        labelEl: "Κυβερνοασφάλεια",
        labelEn: "Cyber",
        tagEl: "Ψηφιακή Ασφάλεια",
        tagEn: "Digital security",
        headlineEl: "Ransomware κάλυψη και Business Interruption ανάλυση.",
        headlineEn: "Ransomware coverage verified, Business Interruption tracked.",
        descEl: "Η ομάδα αντιμετώπισης περιστατικών είναι πάντα ένα tap μακριά. Χωρίς αναζήτηση σε λήξαντα έγγραφα.",
        descEn: "Your incident response team, one tap away. No more hunting through expired PDFs during a breach.",
        surface: "bg-white",
        border: "border-[#E2E8F0]",
        tagBg: "bg-[#F1F5F9] text-[#475569]",
    },
    {
        id: "liability",
        href: "/product/liability",
        icon: Scale,
        labelEl: "Αστική Ευθύνη",
        labelEn: "Liability",
        tagEl: "Τρίτοι",
        tagEn: "Third parties",
        headlineEl: "Ζημιές σε τρίτους — και έλεγχος για διπλή κάλυψη.",
        headlineEn: "Third-party damage — with a double-coverage check built in.",
        descEl: "Η αστική ευθύνη συχνά υπάρχει ήδη μέσα στο συμβόλαιο κατοικίας σας. Δείτε αν την έχετε πριν την αγοράσετε ξανά.",
        descEn: "Liability cover often already sits inside your home policy. See whether you hold it before buying it again.",
        surface: "bg-[#DCEBDA]",
        border: "border-[#A7F3D0]",
        tagBg: "bg-[#F0FDF4] text-[#166534]",
    },
    {
        id: "legal-expenses",
        href: "/product/legal-expenses",
        icon: Gavel,
        labelEl: "Νομική Προστασία",
        labelEn: "Legal Expenses",
        tagEl: "Νομικά",
        tagEn: "Legal",
        headlineEl: "Δικηγόροι και δικαστήρια: τι πληρώνει το συμβόλαιο.",
        headlineEn: "Lawyers and courts: what your policy actually pays for.",
        descEl: "Τροχαία, εργασιακές και καταναλωτικές διαφορές. Δείτε ποιες υποθέσεις καλύπτονται και ποιες εξαιρούνται.",
        descEn: "Traffic, employment and consumer disputes. See which cases are covered and which are excluded.",
        surface: "bg-[#DCEBDA]",
        border: "border-[#A7F3D0]",
        tagBg: "bg-[#F0FDF4] text-[#166534]",
    },
    {
        id: "group-health",
        href: "/product/group-health",
        icon: Users,
        labelEl: "Ομαδική Υγεία",
        labelEn: "Group Health",
        tagEl: "Εταιρικό",
        tagEn: "Corporate",
        headlineEl: "Συντονισμός εταιρικών παροχών με ατομική κάλυψη.",
        headlineEn: "Coordinate corporate benefits with personal coverage.",
        descEl: "Σταματήστε να πληρώνετε δύο φορές για το ίδιο πράγμα. Χαρτογραφήστε τα κενά ανάμεσα σε εταιρικό και ατομικό.",
        descEn: "Stop double-paying for overlapping benefits. Map blind spots between your employer plan and personal policy.",
        surface: "bg-white",
        border: "border-[#E2E8F0]",
        tagBg: "bg-[#F1F5F9] text-[#475569]",
    },
    {
        id: "group-life",
        href: "/product/group-life",
        icon: Umbrella,
        labelEl: "Ομαδική Ζωή",
        labelEn: "Group Life",
        tagEl: "Εταιρικό",
        tagEn: "Corporate",
        headlineEl: "Κεφάλαιο ζωής και ανικανότητας για κάθε εργαζόμενο.",
        headlineEn: "Life and disability capital for every employee.",
        descEl: "Η παροχή που ολοκληρώνει το πακέτο δίπλα στην ομαδική υγεία και σύνταξη. Δείτε ποιος καλύπτεται και με πόσα.",
        descEn: "The benefit that completes the package next to group health and pension. See who is covered and for how much.",
        surface: "bg-white",
        border: "border-[#E2E8F0]",
        tagBg: "bg-[#F1F5F9] text-[#475569]",
    },
    {
        id: "group-pension",
        href: "/product/group-pension",
        icon: TrendingUp,
        labelEl: "Ομαδική Σύνταξη",
        labelEn: "Group Pension",
        tagEl: "Συνταξιοδότηση",
        tagEn: "Retirement",
        headlineEl: "Φορολογικές εκπτώσεις και προβολές αποταμίευσης.",
        headlineEn: "Tax deductions and fund performance projections.",
        descEl: "Ξέρετε πότε να αποχωρήσετε, πόσα έχετε συγκεντρώσει και τι φορολογικές εκπτώσεις σας ανήκουν.",
        descEn: "Know when to retire, how much you've vested, and exactly what tax deductions you're entitled to.",
        surface: "bg-white",
        border: "border-[#E2E8F0]",
        tagBg: "bg-[#F1F5F9] text-[#475569]",
    },
    {
        id: "life",
        href: "/product/life",
        icon: HeartHandshake,
        labelEl: "Ζωή",
        labelEn: "Life",
        tagEl: "Οικογένεια",
        tagEn: "Family",
        headlineEl: "Κεφάλαιο κάλυψης, σοβαρές ασθένειες και προστασία δανείου.",
        headlineEn: "Coverage capital, critical illness and mortgage protection.",
        descEl: "Δείτε αν το κεφάλαιο του συμβολαίου ζωής σας φτάνει πραγματικά για την οικογένεια και το στεγαστικό σας.",
        descEn: "See whether your life policy's capital actually covers your family and your outstanding mortgage.",
        surface: "bg-[#DCEBDA]",
        border: "border-[#A7F3D0]",
        tagBg: "bg-[#F0FDF4] text-[#166534]",
    },
    {
        id: "travel",
        href: "/product/travel",
        icon: Plane,
        labelEl: "Ταξιδιωτική",
        labelEn: "Travel",
        tagEl: "Ταξίδια",
        tagEn: "Trips",
        headlineEl: "Ιατρικά έκτακτα, ακύρωση ταξιδιού και όρια για Σένγκεν.",
        headlineEn: "Emergency medical abroad, trip cancellation and Schengen limits.",
        descEl: "Μάθετε τι καλύπτει η ταξιδιωτική σας ασφάλεια — και αν τα όρια αρκούν για βίζα — πριν φύγετε, όχι στο ταμείο του νοσοκομείου.",
        descEn: "Know what your travel policy covers — and whether limits meet visa requirements — before you fly, not at a foreign hospital.",
        surface: "bg-[#DCEBDA]",
        border: "border-[#A7F3D0]",
        tagBg: "bg-[#F0FDF4] text-[#166534]",
    },
    {
        id: "pension",
        href: "/product/pension",
        icon: PiggyBank,
        labelEl: "Σύνταξη & Αποταμίευση",
        labelEn: "Pension & Savings",
        tagEl: "Μέλλον",
        tagEn: "Future",
        headlineEl: "Εισφορές, ωρίμανση και όροι εξαγοράς χωρίς ψιλά γράμματα.",
        headlineEn: "Contributions, maturity and surrender terms without fine print.",
        descEl: "Καταλάβετε τι έχετε συμφωνήσει: εφάπαξ ή σύνταξη, εγγυημένο σκέλος και τι χάνετε αν εξαγοράσετε νωρίς.",
        descEn: "Understand what you signed: lump sum or annuity, guaranteed component, and what an early surrender costs you.",
        surface: "bg-[#DCEBDA]",
        border: "border-[#A7F3D0]",
        tagBg: "bg-[#F0FDF4] text-[#166534]",
    },
    {
        id: "boat",
        href: "/product/boat",
        icon: Sailboat,
        labelEl: "Σκάφος",
        labelEn: "Boat",
        tagEl: "Θάλασσα",
        tagEn: "Marine",
        headlineEl: "Υποχρεωτική αστική ευθύνη και κάλυψη σκάφους & μηχανής.",
        headlineEn: "Mandatory liability plus hull & machinery coverage.",
        descEl: "Η αστική ευθύνη είναι υποχρεωτική στα ελληνικά ύδατα. Δείτε τι άλλο καλύπτει το συμβόλαιό σας πριν λύσετε κάβους.",
        descEn: "Liability cover is mandatory in Greek waters. See what else your policy includes before you cast off.",
        surface: "bg-[#DCEBDA]",
        border: "border-[#A7F3D0]",
        tagBg: "bg-[#F0FDF4] text-[#166534]",
    },
    {
        id: "business",
        href: "/product/business",
        icon: Briefcase,
        labelEl: "Επιχείρηση",
        labelEn: "Business",
        tagEl: "Επαγγελματικό",
        tagEn: "Commercial",
        headlineEl: "Στέγη, εξοπλισμός, διακοπή εργασιών και ευθύνες μαζί.",
        headlineEn: "Premises, equipment, interruption and liabilities in one view.",
        descEl: "Το πολυασφαλιστήριο της επιχείρησής σας έχει πολλά σκέλη. Δείτε ποια έχετε και ποια λείπουν, σε μία εικόνα.",
        descEn: "A business multi-risk policy has many sections. See which ones you hold and which are missing, at a glance.",
        surface: "bg-white",
        border: "border-[#E2E8F0]",
        tagBg: "bg-[#F1F5F9] text-[#475569]",
    },
    {
        id: "pet",
        href: "/product/pet",
        icon: PawPrint,
        labelEl: "Κατοικίδια",
        labelEn: "Pet",
        tagEl: "Ζώα Συντροφιάς",
        tagEn: "Companion animals",
        headlineEl: "Έλεγχος Leishmania και εξαιρούμενων προϋπαρχουσών παθήσεων.",
        headlineEn: "Leishmania verification and pre-existing condition exclusion audit.",
        descEl: "Ξέρετε ακριβώς τι καλύπτεται και τι δεν καλύπτεται πριν ο κτηνίατρος σας δώσει τον λογαριασμό.",
        descEn: "Know exactly what's covered and what isn't before the vet hands you the bill.",
        surface: "bg-[#DCEBDA]",
        border: "border-[#A7F3D0]",
        tagBg: "bg-[#F0FDF4] text-[#166534]",
    },
] as const satisfies readonly ProductCategory[]

export type ProductCategoryId = (typeof productCategories)[number]["id"]

export function getProductCategory(id: ProductCategoryId) {
    return productCategories.find((category) => category.id === id)
}
