/**
 * Shared fixture access for the ingestion test suite. Reused by every spec that
 * needs the committed, anonymized Greek PDF fixtures (generated by
 * scripts/generate-pipeline-fixtures.mjs).
 */
import { readFile } from "fs/promises"
import path from "path"

export const FIXTURE_DIR = path.join(process.cwd(), "tests/fixtures")

/** Real text-layer Greek policy (pdfjs extracts text; €50.000 + dd/mm/yyyy). */
export const TEXT_LAYER_PDF = path.join(FIXTURE_DIR, "policy-text-layer-el.pdf")
/** Image-only Greek policy (no text layer → triage routes to OCR). */
export const SCANNED_PDF = path.join(FIXTURE_DIR, "policy-scanned-el.pdf")

export function readFixture(filePath: string): Promise<Buffer> {
  return readFile(filePath)
}
